channels:
  - defaults
  - conda-forge

dependencies:
  - pip
  - ipython
  - jupyter
  - numpy
  - nbsphinx
  - numpydoc
  - sphinx>=1.7.5
  - pandoc
  - astropy  # need this here, because we base classes off it (and docs need that).
  - pyyaml
  - matplotlib
  - powerbox
  - pip:
    - sphinx-rtd-theme
    - setuptools_scm
